### ISSUE TITLE
ScrollBar

### ISSUE THREAD

**Issue by SimpleRookie** [mikelovesrobots/unity3d-console#6]
Using this for a server console. Good code. Thank you.

But my scrollbar simply isn't working. Current version of unity. and other then the lidgren in the background this is the only thing in the scene.

Any advice? Also, I have the ConsoleGUI enabled at start.

**Comment by ShaneOBrien** [comment]
I believe I fixed this in my fork if you want to give that a go:

https://github.com/ShaneOBrien/unity3d-console

**Comment by Martins-74** [comment]
@ShaneOBrien your script doésn't work too :(
I trying to fix this issue, but i cant see what is the problem can some one tell me if they a solution...

@SimpleRookie
 @mikelovesrobots 
@ShaneOBrien

**Comment by mikelovesrobots** [comment]
@Martins-74 Sorry for the late response. It's fixed in latest master.
